### ISSUE TITLE
Licence? Can we use this code in our games?

### ISSUE THREAD

**Issue by booyaa** [TerryCavanagh/pico8-game#10]
Can we use the code you've shared in this repo? I've found it invaluable as a new game developer.

**Comment by TerryCavanagh** [comment]
Agh, sorry. I forgot this was public. I've been meaning to make it private.

To be honest, even though I'm not currently actively working on this, it's still a game I'm excited about finishing and I'd be pretty bummed out if someone else took this code and made something else with it before I had a chance to finish it. It took weeks of work to optimise a raycaster to work well in Pico-8.

So, yeah, sorry, but I'd rather you didn't. I'll make this repo private from now on.
