### ISSUE TITLE
optimization - unnecessary parentheses

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/pico8-game#2]
/Users/stephenlavelle/Downloads/pico8-game-master/player.lua:
   30  function moveplayer(dmove)
   31    if not checkwall(posx + dmove * dirx * (movespeed+playerwallbuffer), posy) then
   32:     posx = posx + dmove * (dirx * movespeed)
   33    end
   34    if not checkwall(posx, posy + dmove * diry * (movespeed+playerwallbuffer)) then
   35:     posy = posy + dmove * (diry * movespeed)
   36    end
   37  end

**Comment by TerryCavanagh** [comment]
Done!
