### ISSUE TITLE
optimization, possibly unnecessary local vars

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/pico8-game#3]
/Users/stephenlavelle/Downloads/pico8-game-master/raycast.lua:
   82  function drawstripe(x, layer)
   83    local shootthrough = 0
   84:   local rayformula = rayformula
   85:   local safesqrt = safesqrt
   86:   local flr = flr
   87  
   88    --calculate ray position and direction
   ..
  255      end
  256  
  257:     wallx = wallx - flr(wallx)
  258  
  259      --x coordinate on the texture

**Comment by TerryCavanagh** [comment]
Done!
