### ISSUE TITLE
optimizable mod

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/pico8-game#4]
blocks.lua
function setblocktexture(b, frame, size)
  local block = blocks[b]
  tx = (frame%16)*8
  
  (frame%16)*8
  frame*8%128

**Comment by TerryCavanagh** [comment]
This one didn't work :(

**Comment by increpare** [comment]
what didn't work? and why? think it pasted stuff in incorrectly due to markup. maybe this'll work

	(frame%16)*8 --7 tokens
	frame*8 % 128 --5 tokens
