### ISSUE TITLE
optimzation local variable

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/pico8-game#6]
pathfinding.lua

  local function checkpathsquare(x, y, t)
    if(mget(x,y) == 0) then
     
      local h=heatmap[x][y]
      if h == 0 or t < h then
      

      if heatmap[x][y] == 0 or t < heatmap[x][y] then
        heatmap[x][y] = t

**Comment by TerryCavanagh** [comment]
:tangerine:
