### ISSUE TITLE
optimization - strip out global constants

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/pico8-game#8]
unnecessary
raycast.lua
pi = 3.14159265358979
wallbuffer = 0.5
playerwallbuffer = 0.3
turnspeed = 0.0174532925199433 --pi/180
movespeed = 0.15
showfloor = true
showceiling = true
uselighting = true
ceilingcol = 0
floorcol = 0
w = 48
h = 48
wallheight = 38--(50/64)*h
texwidth = 8
texheight = 8

**Comment by TerryCavanagh** [comment]
maybe I'll leave this one as a last resort :cat:
